-- Definition sync: local -> prod.
-- Replaces prod item/object/npc/action/skill definitions with the local set.
-- Load on prod:  psql "postgresql://postgres:admin@localhost:5432/mmo" -f prod_defs_sync.sql
BEGIN;
SET session_replication_role = replica;  -- skip FK checks during bulk load
TRUNCATE object_definitions, npc_definitions, npc_drops, item_definitions, action_definitions, skill_definitions RESTART IDENTITY CASCADE;
INSERT INTO public.action_definitions VALUES ('chop', 'Chop', 'gather_resource');
INSERT INTO public.action_definitions VALUES ('mine', 'Mine', 'gather_resource');
INSERT INTO public.action_definitions VALUES ('fish', 'Fish', 'gather_resource');
INSERT INTO public.action_definitions VALUES ('harvest', 'Harvest', 'gather_resource');
INSERT INTO public.action_definitions VALUES ('smith', 'Smith', 'production_facility');
INSERT INTO public.action_definitions VALUES ('cook', 'Cook', 'production_facility');
INSERT INTO public.action_definitions VALUES ('equip', 'Equip', 'equip');
INSERT INTO public.action_definitions VALUES ('eat', 'Eat', 'eat');
INSERT INTO public.action_definitions VALUES ('talk', 'Talk-to', 'talk');
INSERT INTO public.action_definitions VALUES ('bank', 'Bank', 'bank');
INSERT INTO public.action_definitions VALUES ('examine', 'Examine', 'examine');
INSERT INTO public.item_definitions VALUES ('coins', 'Coins', true, true, 1, NULL, 'resource', NULL, false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('oak_logs', 'Oak logs', false, true, 25, NULL, 'resource', NULL, false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('willow_logs', 'Willow logs', false, true, 40, NULL, 'resource', NULL, false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('tin_ore', 'Tin ore', false, true, 8, NULL, 'resource', NULL, false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('iron_ore', 'Iron ore', false, true, 30, NULL, 'resource', NULL, false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('bronze_bar', 'Bronze bar', false, true, 20, NULL, 'resource', NULL, false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('iron_bar', 'Iron bar', false, true, 55, NULL, 'resource', NULL, false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('shrimp', 'Shrimp', false, true, 10, NULL, 'food', NULL, false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('raw_trout', 'Raw trout', false, true, 15, NULL, 'resource', NULL, false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('trout', 'Trout', false, true, 30, NULL, 'food', NULL, false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('tinderbox', 'Tinderbox', false, true, 1, NULL, 'resource', NULL, false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('arrow', 'Bronze arrow', true, true, 1, NULL, 'equipment', 'ammo', false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('axe', 'Bronze axe', false, true, 16, NULL, 'equipment', 'rightHand', false, 4, 0, 0, 0, 0, 0, 'woodcutting', 1, 'axe', NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('bronze_sword', 'Bronze sword', false, true, 40, NULL, 'equipment', 'rightHand', false, 6, 3, 0, 0, 0, 0, NULL, NULL, NULL, 'melee', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('iron_sword', 'Iron sword', false, true, 120, NULL, 'equipment', 'rightHand', false, 10, 5, 0, 0, 0, 0, NULL, NULL, NULL, 'melee', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('bronze_shield', 'Bronze shield', false, true, 30, NULL, 'equipment', 'leftHand', false, 0, 0, 5, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('leather_helm', 'Leather helm', false, true, 20, NULL, 'equipment', 'head', false, 0, 0, 1, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('bronze_helm', 'Bronze helm', false, true, 80, NULL, 'equipment', 'head', false, 0, 0, 3, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('leather_body', 'Leather body', false, true, 30, NULL, 'equipment', 'body', false, 0, 0, 2, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('leather_legs', 'Leather legs', false, true, 25, NULL, 'equipment', 'legs', false, 0, 0, 1, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('leather_gloves', 'Leather gloves', false, true, 10, NULL, 'equipment', 'hands', false, 0, 0, 1, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('leather_boots', 'Leather boots', false, true, 15, NULL, 'equipment', 'feet', false, 0, 0, 1, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('gold_ring', 'Gold ring', false, true, 50, NULL, 'equipment', 'ring', false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('amulet', 'Amulet of str', false, true, 200, NULL, 'equipment', 'neck', false, 0, 4, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('bronze_longsword', 'Bronze longsword', false, true, 60, 'Careful not to poke your eye out!', 'equipment', 'rightHand', false, 8, 7, 0, 0, 0, 0, NULL, NULL, NULL, 'melee', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('kinetic_charges', 'Kinetic Charges', true, true, 1, NULL, 'equipment', 'ammo', false, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('basic_chaingun', 'Basic Chaingun', false, true, 200, 'A heavy two-handed energy weapon.', 'equipment', 'rightHand', true, 0, 0, 0, 8, 4, 0, NULL, NULL, NULL, 'gunner', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('iron_axe', 'Iron axe', false, true, 8, '', 'equipment', 'rightHand', false, -1, 0, 2, 0, 0, 0, 'woodcutting', 1, 'axe', '', 0, 'assets/sprites/items/woodcutting.png', 'assets/models/iron_axe_drop.glb', 'assets/models/iron_axe.glb', '', -0.035, 0.03, -0.085, 90, 0, 180, 1);
INSERT INTO public.item_definitions VALUES ('pickaxe', 'Iron Pickaxe', false, true, 25, 'A sturdy iron pickaxe, good for mining.', 'equipment', 'rightHand', false, 6, 0, 1, 0, 0, 0, 'mining', 1, 'pickaxe', '', 0, 'assets/sprites/items/Pickaxe.png', 'assets/models/iron_pickaxe_drop.glb', 'assets/models/iron_pickaxe.glb', '', -0.03, 0.065, -0.08, 90, 0, 90, 1);
INSERT INTO public.item_definitions VALUES ('fishing_rod', 'Fishing rod', false, true, 5, 'Used to catch fish.', 'resource', '', false, 0, 0, 0, 0, 0, 0, 'fishing', 1, 'fishing_rod', '', 0, 'assets/sprites/items/FishingRod.png', 'assets/models/fishing_rod_drop.glb', 'assets/models/fishing_rod.glb', '', -0.015, 0.08, -0.155, 90, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('raw_shrimp', 'Raw shrimp', false, true, 5, '', 'resource', '', false, 0, 0, 0, 0, 0, 0, '', 0, '', '', 0, 'assets/sprites/items/Raw_Shrimp.png', '', '', NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('copper_ore', 'Copper ore', false, true, 8, '', 'resource', '', false, 0, 0, 0, 0, 0, 0, '', 0, '', '', 0, 'assets/sprites/items/Copper.png', '', '', NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('logs', 'Logs', false, true, 10, 'Yup.', 'resource', '', false, 0, 0, 0, 0, 0, 0, '', 0, '', '', 0, 'assets/sprites/items/Log.png', '', '', NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.item_definitions VALUES ('egg', 'Egg', false, true, 2, '', 'resource', '', false, 0, 0, 0, 0, 0, 0, '', 0, '', '', 0, 'assets/sprites/items/Egg.png', '', '', NULL, 0, 0, 0, 0, 0, 0, 1);
INSERT INTO public.npc_definitions VALUES ('chicken', 'Chicken', 'assets/models/chicken.glb', 1, 1, true, 3, 1, 1, 1, 0, 16, 150, false, '', 'wander', 'It''s a chicken.');
INSERT INTO public.npc_definitions VALUES ('shopkeeper', 'Shopkeeper', 'assets/models/npc_pawn.gltf', 1, 1, false, 10, 0, 0, 0, 0, 0, 0, true, '', 'static', 'This is a friendly shopkeeper.');
INSERT INTO public.npc_drops VALUES ('chicken', 'egg', 1, 1);
INSERT INTO public.object_definitions VALUES ('fence', 'Fence', NULL, 'Decoration', 'half_blocking', 1, 1, NULL, NULL, NULL, NULL, 1, 0, NULL, 'A wooden fence.', NULL, true, 0, 0, 0, NULL, true);
INSERT INTO public.object_definitions VALUES ('tree_stump', 'Tree Stump', 'assets/models/Tree_Stump.glb', 'Decoration', 'full_blocking', 1, 1, NULL, NULL, 0, NULL, 1, 25, NULL, 'A simple tree stump.', NULL, true, 0, 0, 0, NULL, false);
INSERT INTO public.object_definitions VALUES ('tree', 'Tree', 'assets/models/Tree.glb', 'ResourceNode', 'full_blocking', 1, 1, 'chop', 'woodcutting', 1, 'logs', 1, 25, NULL, 'A sturdy tree.', NULL, true, 0, 0, 0, 'tree_stump', true);
INSERT INTO public.object_definitions VALUES ('rock', 'Rock', 'assets/models/Rock.glb', 'ResourceNode', 'full_blocking', 1, 1, 'mine', 'mining', 1, 'copper_ore', 1, 50, NULL, 'A rocky outcrop.', NULL, true, 0, 0, 0, NULL, true);
INSERT INTO public.object_definitions VALUES ('fishing_spot', 'Fishing Spot', 'assets/models/fishing_spot.glb', 'ResourceNode', 'none', 1, 1, 'fish', NULL, 1, 'raw_shrimp', 1, 10, NULL, 'A calm fishing spot.', 'Swimming.001', true, 0, 0, 0, NULL, true);
INSERT INTO public.object_definitions VALUES ('chest', 'Chest', 'assets/models/Chest.glb', 'Decoration', 'full_blocking', 1, 1, 'bank', NULL, 0, NULL, 1, 0, NULL, 'A secure bank chest.', NULL, true, 0, 0, 0, NULL, true);
INSERT INTO public.object_definitions VALUES ('test_wall', 'Test Wall', 'assets/models/wall_test.glb', 'Wall', 'none', 1, 1, NULL, NULL, 0, NULL, 1, 25, NULL, NULL, NULL, true, 0, 0, 0, NULL, false);
INSERT INTO public.object_definitions VALUES ('grass_test', 'Grass', 'assets/models/grass_test.glb', 'Decoration', 'none', 1, 1, NULL, NULL, 0, NULL, 1, 25, NULL, NULL, NULL, true, 0, 0, 0, NULL, false);
INSERT INTO public.object_definitions VALUES ('wall_corner', 'Wall (Corner)', 'assets/models/wall_corner.glb', 'Wall', 'none', 1, 1, NULL, NULL, 0, NULL, 1, 25, NULL, NULL, NULL, true, 0, 0, 0, NULL, false);
INSERT INTO public.object_definitions VALUES ('wall_side', 'Wall (Side)', 'assets/models/wall_side.glb', 'Wall', 'none', 1, 1, NULL, NULL, 0, NULL, 1, 25, NULL, NULL, NULL, true, 0, 0, 0, NULL, false);
INSERT INTO public.object_definitions VALUES ('wall_side_window', 'Wall (Side Window)', 'assets/models/wall_side_window.glb', 'Wall', 'none', 1, 1, NULL, NULL, 0, NULL, 1, 25, NULL, NULL, NULL, true, 0, 0, 0, NULL, false);
INSERT INTO public.object_definitions VALUES ('cactus_saguaro', 'Cactus', 'assets/models/cactus.glb', 'Decoration', 'full_blocking', 1, 1, NULL, NULL, 0, NULL, 1, 25, NULL, NULL, NULL, true, 0, 0, 0, NULL, true);
INSERT INTO public.skill_definitions VALUES ('hitpoints', 'Hitpoints', NULL, 0);
INSERT INTO public.skill_definitions VALUES ('defence', 'Defence', NULL, 1);
INSERT INTO public.skill_definitions VALUES ('woodcutting', 'Woodcutting', 'assets/sprites/skills/woodcutting.png', 4);
INSERT INTO public.skill_definitions VALUES ('mining', 'Mining', 'assets/sprites/skills/Pickaxe.png', 5);
INSERT INTO public.skill_definitions VALUES ('fishing', 'Fishing', 'assets/sprites/skills/FishingRod.png', 6);
INSERT INTO public.skill_definitions VALUES ('warrior', 'Warrior', 'assets/sprites/skills/warrior.png', 2);
INSERT INTO public.skill_definitions VALUES ('gunner', 'Cowboy', 'assets/sprites/skills/Cowboy.png', 3);
SET session_replication_role = DEFAULT;
COMMIT;
